### PR TITLE
Hello world!

### PR DESCRIPTION
**Pull request by JayRovacsek**
First draft of the repository, including: 
* charter documents
* contributing guide
* tooling configuration (optional - but consistently applied in CICD)

### CODE REVIEW

**Review by nephalemsec — APPROVED** [review]
Looks fantastic, love the pre commit hooks!

**Review by colecornford — APPROVED** [review]
It all looks good to me. I'm not really sure about the nix components but I read the charter and think its good and contribution is as well.

**Comment by JayRovacsek** [comment]
> It all looks good to me. I'm not really sure about the nix components but I read the charter and think its good and contribution is as well.

Thanks! I might make a change to the contributing document that puts the most common tooling and short path first: a [single line docker command](https://github.com/Newcastle-Cyber-Security-Group/charter/blob/init/CONTRIBUTING.md#docker) - but the tooling is as described, optional - simply enforcing the style, linting, typo checks I believe will enable us to keep the repo pretty clean with very little effort

**Review by DeClemo — COMMENTED** [review]
Seems like a good start to me :)

**Pull request merged**
